name = "librefit-website-525957" 

# This tells Wrangler that this is a Cloudflare Pages project.
# It specifies the directory containing the static assets (HTML, CSS).
pages_build_output_dir = "public"

# This enables Node.js APIs
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# This creates the Rate Limiter binding in the production environment
[[env.production.ratelimits]]
# This is the variable name uses in the code (context.env.RATE_LIMITER).
name = "RATE_LIMITER" 
# This is a unique number for this rule within the account.
namespace_id = "1001"
# 1 request every minute (60 seconds).
simple = { limit = 1, period = 60 }